Repository WHERE-P/WHERE-Frontend, pull requests merged in 2023-06, with the labels that each got.

#6 [#5] toastify 라이브러리 추가
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: ⚙ Setting

#9 [#8] 폰트적용
  public/fonts/SUIT-Bold.otf
  public/fonts/SUIT-ExtraBold.otf
  public/fonts/SUIT-ExtraLight.otf
  public/fonts/SUIT-Heavy.otf
  public/fonts/SUIT-Light.otf
  public/fonts/SUIT-Medium.otf
  public/fonts/SUIT-Regular.otf
  public/fonts/SUIT-SemiBold.otf
  public/fonts/SUIT-Thin.otf
  public/fonts/style.css
  src/styles/globals.tsx
Labels: ⚡️ Simple

#11 [#10] 헤더 제작
  src/asset/png/WhereLogo.png
  src/asset/svg/LogoutIcon.svg
  src/asset/svg/index.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
Labels: 🎨 Publishing

#13 [#12] 로그인 기능구현
  package.json
  src/api/user.ts
  src/components/Login/molecules/LoginForm/index.tsx
  src/pages/_app.tsx
  src/utils/libs/apiClient.ts
  src/utils/libs/getRefresh.ts
  src/utils/libs/getToken.ts
  src/utils/libs/requestUrls.ts
  src/utils/libs/setToken.ts
  yarn.lock
Labels: ✨ Feature
