Repository WHERE-P/WHERE-Frontend, pull requests merged in 2023-07, with the labels that each got.

#15 [#14] 로그아웃
  src/components/common/Header/index.tsx
  src/utils/libs/logout.ts
  src/utils/libs/removeToken.ts
Labels: ✨ Feature

#16 [#4] 메인 페이지 제작
  src/api/user.ts
  src/asset/data/StateData.ts
  src/asset/svg/Filter.svg
  src/asset/svg/index.ts
  src/components/Home/atoms/FilterButton/index.tsx
  src/components/Home/atoms/FilterButton/style.ts
  src/components/Home/atoms/StuItem/index.tsx
  src/components/Home/atoms/StuItem/style.ts
  src/components/Home/molecules/FilterBox/index.tsx
  src/components/Home/molecules/FilterBox/style.ts
  src/components/Home/molecules/StateDropDown/index.tsx
  src/components/Home/molecules/StateDropDown/style.ts
  src/components/Home/organisms/FilterCheck/index.tsx
  src/components/Home/organisms/FilterCheck/style.ts
  src/components/Home/organisms/ModifyStuInfo/index.tsx
  src/components/Home/organisms/ModifyStuInfo/style.ts
  src/components/Home/organisms/StuList/index.tsx
  src/components/Home/organisms/StuList/style.ts
  src/components/Home/templates/style.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/Modal/style.ts
  src/pages/index.tsx
  src/recoilAtoms/index.ts
  src/utils/libs/requestUrls.ts
Labels: ✨ Feature, 🎨 Publishing

#17 사소한 이슈 수정
  src/components/Home/molecules/StateDropDown/style.ts
  src/components/Home/organisms/FilterCheck/index.tsx
  src/components/Home/organisms/ModifyStuInfo/index.tsx
  src/components/Home/organisms/StuList/index.tsx
Labels: 🐞 Bug
